### ISSUE TITLE
Example 04 is not runnable

### ISSUE THREAD

**Issue by EAGrahamJr** [sparkfun/Qwiic_Alphanumeric_Py#2]
```
$ python3 qwiic_alphanumeric_ex04_set_brightness.py

SparkFun Qwiic Alphanumeric - Example 5: Set Brightness

Qwiic Alphanumeric Ready!
Traceback (most recent call last):
  File "qwiic_alphanumeric_ex04_set_brightness.py", line 70, in <module>
    run_example()
  File "qwiic_alphanumeric_ex04_set_brightness.py", line 65, in run_example
    my_display.display_print("Milk")
AttributeError: 'QwiicAlphanumeric' object has no attribute 'display_print'
```

**Comment by sfe-SparkFro** [comment]
Looks like

https://github.com/sparkfun/Qwiic_Alphanumeric_Py/blob/594e4d99a8051d5af514cd74a15d2a9b8280dfb2/examples/qwiic_alphanumeric_ex04_set_brightness.py#L65

was incorrectly copy/pasted or something, should be updated to be `my_display.print("Milk")`
